name: supermarket
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  stylish_bottom_bar: ^1.0.3
  easy_localization: ^3.0.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.1
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  adaptive_theme: ^3.6.0
  fluttertoast: ^8.2.4
  # * v.v.v.v.imp add delegates Form Builder Validate easy localization
  form_builder_validators: ^9.1.0
  modal_bottom_sheet: ^3.0.0-pre
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.15.5
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  path: ^1.8.3
  webview_flutter: ^4.4.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets :
    - assets/images/products/
    - assets/icons/
    - assets/images/categories/
    - assets/images/slider/
    - assets/logo/
    - assets/images/
    - assets/translations/
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo.jpg"

flutter_native_splash:
  android: true
  ios: true
  web: false
  # Android (11-) + ios
  background_image: assets/images/bg_splash.jpeg
  image: assets/logo/logo1.png

  # Android (12+)
  android_12:
      image: assets/logo/supermarket_logo.jpg
      icon_background_color: "#ffffff"
      image_dark: assets/logo/supermarket_logo.jpg
      icon_background_color_dark: "#121212"